In [1]:
import tensorflow as tf
tf.__version__

'2.7.0'

#### Tensorflow :

* It made up of Tensors which are n dimensional arrays
* Tensors are generalisation of matrices and vectors to higher dimensions
* Tensorflow is made up of graphs and sessions
* Each tensor has a datatype and shape
* Tensors define partially defined computations which produces value later
* Builds a graph of different tensor objects
* Running different parts of the graph generates results

In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


#### Tensors:

In [3]:
s1 = tf.Variable("sample string", tf.string)
s2 = tf.Variable(123, tf.int64)
s3 = tf.Variable(32.56, tf.float64)

In [4]:
s1.shape

TensorShape([])

In [5]:
# Rank/Degree - No of dimensions involved in the tensor
tf.rank(s1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [6]:
tf.rank(s2)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [7]:
var = tf.ones([1,2,3])
var

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [9]:
var = tf.reshape(3,-1)
var

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

### Types of Tensors:

* Variable
* Constant
* Placeholder
* SparseTensor

Except variable, all others are immutable

In [17]:
var_2 = tf.zeros([4,4,4,4])
var_2

<tf.Tensor: shape=(4, 4, 4, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
        

In [18]:
var_2.shape

TensorShape([4, 4, 4, 4])

In [19]:
tf.rank(var_2)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [20]:
var_2 = tf.reshape(var_2, [64, -1])
var_2.shape

TensorShape([64, 4])

In [21]:
tf.rank(var_2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [22]:
var_2

<tf.Tensor: shape=(64, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
 